"""Guard: every non-Python file inside the package is declared as package data.

``ui/icons/*.svg`` are read from disk at runtime (``icons.ICON_DIR``). Without a
``[tool.setuptools.package-data]`` entry setuptools silently leaves them out, so
the wheel — and the PyInstaller build that collects the installed package —
produces an application whose navigation rail has no icons at all. Nothing
crashes, which is exactly why this has to be a test.
"""
from __future__ import annotations

import fnmatch
import re
import struct
import tomllib
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
PACKAGE = ROOT / "src" / "qtrequestory"
IGNORED_DIRS = {"__pycache__"}


def _package_data() -> dict[str, list[str]]:
    with (ROOT / "pyproject.toml").open("rb") as f:
        config = tomllib.load(f)
    return config["tool"]["setuptools"]["package-data"]


def _data_files() -> list[Path]:
    """Every shipped non-``.py`` file, relative to ``src/qtrequestory``."""
    return sorted(
        p.relative_to(PACKAGE)
        for p in PACKAGE.rglob("*")
        if p.is_file() and p.suffix != ".py" and not IGNORED_DIRS & set(p.parts)
    )


def _is_declared(relative: Path, declared: dict[str, list[str]]) -> bool:
    """True when some declared pattern covers ``relative`` (as setuptools reads it)."""
    for package, patterns in declared.items():
        prefix = "" if package == "*" else package.removeprefix("qtrequestory.").replace(".", "/")
        for pattern in patterns:
            candidate = f"{prefix}/{pattern}" if prefix else pattern
            if fnmatch.fnmatch(relative.as_posix(), candidate):
                return True
    return False


def test_every_data_file_in_the_package_is_declared():
    declared = _package_data()
    missing = [str(f) for f in _data_files() if not _is_declared(f, declared)]
    assert not missing, f"not covered by [tool.setuptools.package-data]: {missing}"


def test_the_icons_really_are_data_files():
    """A sanity check on the test above: it would pass on an empty package too."""
    names = {f.name for f in _data_files()}
    assert "app.svg" in names
    assert "arrow-sync.svg" in names


# --------------------------------------------------------------- app.ico ---
#
# The Windows shell reads the exe's icon resource; the ``.ico`` is generated by
# ``scripts/make_icon.py`` and committed so that a plain
# ``pyinstaller qtRequestory.spec`` needs no Qt pre-step. ``icons.app_icon()``
# also loads it at runtime for the window icon, so it is bundled as data too. A
# container Windows silently refuses (a missing size, a wrong offset) would only
# show up as a blank icon on a colleague's taskbar.

ICO = PACKAGE / "ui" / "icons" / "app.ico"
EXPECTED_ICON_SIZES = {16, 20, 24, 32, 40, 48, 64, 256}


def _ico_entries(data: bytes) -> list[tuple[int, int, int, int]]:
    """``(width, height, length, offset)`` per ICONDIRENTRY; 0 in the byte means 256."""
    reserved, kind, count = struct.unpack_from("<HHH", data, 0)
    assert (reserved, kind) == (0, 1), "not an ICO file"
    entries = []
    for i in range(count):
        w, h, _colors, _res, _planes, _bits, length, offset = struct.unpack_from(
            "<BBBBHHII", data, 6 + 16 * i
        )
        entries.append((w or 256, h or 256, length, offset))
    return entries


def test_app_ico_holds_every_size_the_shell_asks_for():
    entries = _ico_entries(ICO.read_bytes())
    assert {w for w, _h, _length, _offset in entries} == EXPECTED_ICON_SIZES
    assert all(w == h for w, h, _length, _offset in entries), "non-square icon entry"


def test_spec_bundles_app_ico():
    """``app_icon()`` reads ``app.ico`` from ICON_DIR, which in the exe is the bundle."""
    spec = SPEC.read_text(encoding="utf-8")
    assert re.search(
        r"\(\s*str\(\s*ICON_DIR\s*/\s*['\"]app\.ico['\"]\s*\)\s*,\s*['\"]qtrequestory/ui/icons['\"]\s*\)",
        spec,
    ), "qtRequestory.spec does not list app.ico in datas"


def test_app_ico_entries_point_inside_the_file():
    """A wrong offset/length is exactly the bug that renders as a blank icon."""
    data = ICO.read_bytes()
    for width, _h, length, offset in _ico_entries(data):
        assert length > 0, f"empty {width}px entry"
        assert offset + length <= len(data), f"{width}px entry runs past the end of the file"


# ------------------------------------------------ dynamic imports vs. the spec ---
#
# PyInstaller builds its module graph statically. A module reached through
# ``importlib.import_module(<computed name>)`` is invisible to it and is simply
# left out of the exe — and ``MainWindow._build_page`` deliberately swallows the
# resulting ModuleNotFoundError, so the packaged application starts, draws the
# navigation rail, and shows "La pagina X non è disponibile in questa versione."
# on every single page. It happened on the first build of this project.
#
# Every dynamically imported package therefore has to be *collected* by
# ``qtRequestory.spec``, and the collection has to reach ``hiddenimports``.

SPEC = ROOT / "qtRequestory.spec"
#: Every shape that hides a module name from PyInstaller's static analysis:
#: ``importlib.import_module(...)``, the ``from importlib import import_module``
#: variant that calls it bare, and the ``__import__`` builtin.
DYNAMIC_IMPORT = re.compile(
    r"\bimportlib\s*\.\s*import_module\s*\("   # the canonical spelling
    r"|(?<!\.)\bimport_module\s*\("            # `from importlib import import_module`
    r"|(?<!\.)\b__import__\s*\("               # the builtin
)
#: file -> the package name (a module-level constant) it imports from dynamically.
KNOWN_DYNAMIC_IMPORTERS = {"ui/main_window.py": "qtrequestory.ui.pages"}


def _modules_using_dynamic_import() -> set[str]:
    return {
        p.relative_to(PACKAGE).as_posix()
        for p in PACKAGE.rglob("*.py")
        if DYNAMIC_IMPORT.search(p.read_text(encoding="utf-8"))
    }


def test_the_spec_collects_every_dynamically_imported_package():
    """The spec must *call* collect_submodules, not merely mention the package.

    An earlier version of this test asserted ``package in spec`` over the whole
    file. The package name also appears in the spec's own comments, so deleting
    the ``collect_submodules`` call and the ``hiddenimports=`` line left the test
    green while the exe went back to shipping four placeholder pages. Match the
    code.
    """
    spec = SPEC.read_text(encoding="utf-8")
    for package in KNOWN_DYNAMIC_IMPORTERS.values():
        collected = re.search(
            rf"collect_submodules\(\s*['\"]{re.escape(package)}['\"]\s*\)", spec
        )
        assert collected, f"qtRequestory.spec never calls collect_submodules({package!r})"
    assert "hiddenimports=PAGE_MODULES" in spec, (
        "qtRequestory.spec collects the page modules but does not pass them to "
        "Analysis(hiddenimports=...), so they never reach the exe"
    )


@pytest.mark.parametrize("line", [
    "    page = importlib.import_module(name)",
    "    page = import_module(name)",                 # from importlib import import_module
    "    page = import_module(f'{PKG}.{module}')",
    "    page = __import__(name, fromlist=['x'])",
    "mod = importlib .import_module(name)",           # spacing does not help it hide
    "mod = import_module (name)",
])
def test_the_detector_sees_every_shape_of_dynamic_import(line):
    """The first version of this regex only knew ``importlib.import_module(``."""
    assert DYNAMIC_IMPORT.search(line)


@pytest.mark.parametrize("line", [
    "from importlib import import_module",            # the import itself is not a call
    "import importlib",
    "self.import_module_count += 1",
    "obj.import_module(name)",                        # a method of something else
])
def test_the_detector_does_not_cry_wolf(line):
    assert not DYNAMIC_IMPORT.search(line)


def test_the_package_name_the_spec_relies_on_is_the_real_one():
    """Renaming ``PAGES_PACKAGE`` without touching the spec must not pass silently."""
    source = (PACKAGE / "ui" / "main_window.py").read_text(encoding="utf-8")
    assert 'PAGES_PACKAGE = "qtrequestory.ui.pages"' in source


def test_no_new_dynamic_import_slips_in_unnoticed():
    found = _modules_using_dynamic_import()
    unexpected = found - set(KNOWN_DYNAMIC_IMPORTERS)
    assert not unexpected, (
        f"{sorted(unexpected)} import modules dynamically: add the package to "
        f"qtRequestory.spec's hidden imports, then list the file here"
    )
    assert found == set(KNOWN_DYNAMIC_IMPORTERS), (
        "a file listed in KNOWN_DYNAMIC_IMPORTERS no longer imports dynamically; "
        "drop it here (and from the spec if nothing else needs it)"
    )


def test_dev_scripts_are_not_shipped():
    """``scripts/dev`` (screenshot harness, fake core) is for developers only.

    The exe is built from ``scripts/entrypoint.py`` alone and the wheel from
    ``src/``; neither may start pulling in the dev tools.
    """
    assert (ROOT / "scripts" / "dev" / "shoot.py").is_file()
    spec = SPEC.read_text(encoding="utf-8")
    assert '[str(SCRIPTS / "entrypoint.py")]' in spec
    assert "dev" not in re.findall(r"SCRIPTS\s*/\s*\"([^\"]+)\"", spec)
    assert "shoot" not in spec
    assert not (PACKAGE / "dev").exists()
