"""qtrequestory.officina.compare.extract_pdf: words with boxes from a PDF.

PDFs are generated by Qt (tests/officina/pdfgen.py) from synthetic text only.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
from pathlib import Path

import pytest

from qtrequestory.officina.compare import extract_pdf
from qtrequestory.officina.compare.extract_pdf import DocText, Word, extract
from tests.officina import pdfgen

SRC = Path(__file__).resolve().parents[2] / "src"


def test_words_have_boxes_in_points_from_the_top_left(pdfs: Path):
    path = pdfgen.paragraphs_pdf(pdfs / "a.pdf", ["Alfa beta gamma"] + ["riempitivo"] * 3)
    doc = extract(path)
    assert isinstance(doc, DocText)
    assert doc.has_text
    assert [w.text for w in doc.words[:3]] == ["Alfa", "beta", "gamma"]
    w, h = doc.page_sizes[0]
    assert w == pytest.approx(595, abs=1) and h == pytest.approx(842, abs=1)
    first = doc.words[0]
    assert isinstance(first, Word) and first.page == 0
    assert 0 <= first.x0 < first.x1 <= w
    assert 0 <= first.y0 < first.y1 < h / 4, "the first line sits near the TOP of the page"
    beta = doc.words[1]
    assert beta.x0 > first.x1, "words on one line go left to right"
    assert beta.y0 == pytest.approx(first.y0, abs=2)


def test_reading_order_is_top_to_bottom_then_left_to_right(pdfs: Path):
    path = pdfgen.paragraphs_pdf(pdfs / "a.pdf", ["uno due", "tre quattro", "cinque sei"])
    words = extract(path).words
    assert [w.text for w in words] == ["uno", "due", "tre", "quattro", "cinque", "sei"]
    assert words[2].y0 > words[0].y1


def test_punctuation_stays_attached_to_its_word(pdfs: Path):
    path = pdfgen.paragraphs_pdf(pdfs / "a.pdf", ["Primo, secondo; terzo."])
    assert [w.text for w in extract(path).words] == ["Primo,", "secondo;", "terzo."]


def test_line_end_hyphen_is_extracted_as_a_hyphen(pdfs: Path):
    path = pdfgen.html_pdf(pdfs / "a.pdf", "<p>Il para-<br>grafo continua</p>")
    assert [w.text for w in extract(path).words] == ["Il", "para-", "grafo", "continua"]


def test_pages_are_numbered_and_sized(pdfs: Path):
    text = pdfgen.lorem(1500)
    doc = extract(pdfgen.paragraphs_pdf(pdfs / "a.pdf", [text]))
    assert len(doc.page_sizes) >= 2
    assert doc.words[0].page == 0 and doc.words[-1].page == len(doc.page_sizes) - 1
    pages = [w.page for w in doc.words]
    assert pages == sorted(pages)
    assert " ".join(w.text for w in doc.words) == text


def test_image_only_pdf_has_no_text(pdfs: Path):
    doc = extract(pdfgen.image_only_pdf(pdfs / "scan.pdf", pages=2))
    assert doc.has_text is False
    assert doc.words == []
    assert len(doc.page_sizes) == 2


def test_extract_pdf_imports_pypdfium2_only_through_officina_pdf():
    source = Path(extract_pdf.__file__).read_text(encoding="utf-8")
    assert not re.search(r"^\s*(import|from)\s+pypdfium2", source, re.MULTILINE)


@pytest.mark.parametrize("module", [
    "qtrequestory.officina.compare",
    "qtrequestory.officina.compare.textdiff",
    "qtrequestory.officina.compare.extract_pdf",
    "qtrequestory.officina.compare.edge",
])
def test_importing_compare_modules_does_not_load_pypdfium2(module: str):
    code = f"import sys, {module}; print(any(m.startswith('pypdfium2') for m in sys.modules))"
    env = {**os.environ, "PYTHONPATH": str(SRC)}
    out = subprocess.run([sys.executable, "-c", code], capture_output=True, text=True,
                         check=True, env=env).stdout.strip()
    assert out == "False"


def _variant(src: Path, out: Path, change) -> Path:
    """A copy of ``src`` whose first page is changed by ``change(page)`` (pypdfium2)."""
    import pypdfium2 as pdfium  # test-only: builds the fixture, the code under test never does

    doc = pdfium.PdfDocument(str(src))
    page = doc[0]
    change(page)
    page.close()
    doc.save(str(out))
    doc.close()
    return out


W, H = 595.0, 842.0
#: /Rotate turns the page clockwise; where an upright box (top-left points) lands.
ROTATED_BOX = {
    90: ((H, W), lambda x0, y0, x1, y1: (H - y1, x0, H - y0, x1)),
    180: ((W, H), lambda x0, y0, x1, y1: (W - x1, H - y1, W - x0, H - y0)),
    270: ((H, W), lambda x0, y0, x1, y1: (y0, W - x1, y1, W - x0)),
}


@pytest.mark.parametrize("rotation", [90, 180, 270])
def test_rotated_page_keeps_every_word_in_displayed_coordinates(pdfs: Path, rotation: int):
    base = pdfgen.paragraphs_pdf(pdfs / "base.pdf", ["Alfa beta gamma"] + ["riempitivo parola"] * 20)
    rotated = _variant(base, pdfs / "rot.pdf", lambda p: p.set_rotation(rotation))
    before = rotated.read_bytes()
    upright, turned = extract(base), extract(rotated)
    assert rotated.read_bytes() == before, "extraction never writes the file"
    assert [w.text for w in turned.words] == [w.text for w in upright.words]
    size, move = ROTATED_BOX[rotation]
    assert turned.page_sizes[0] == pytest.approx(size, abs=1)
    width, height = turned.page_sizes[0]
    for a, b in zip(upright.words, turned.words):
        assert (b.x0, b.y0, b.x1, b.y1) == pytest.approx(move(a.x0, a.y0, a.x1, a.y1), abs=0.05)
        assert 0 <= b.x0 < b.x1 <= width and 0 <= b.y0 < b.y1 <= height


def test_rotated_and_cropped_page(pdfs: Path):
    base = pdfgen.paragraphs_pdf(pdfs / "base.pdf", ["Alfa beta gamma"] + ["riempitivo parola"] * 20)

    def change(page):
        page.set_cropbox(20, 30, 580, 830)
        page.set_rotation(180)

    both = extract(_variant(base, pdfs / "both.pdf", change))
    upright = extract(base)
    assert [w.text for w in both.words] == [w.text for w in upright.words]
    assert both.page_sizes[0] == pytest.approx((560, 800), abs=0.5)
    for a, b in zip(upright.words, both.words):
        # crop origin (20, 12) top-left, then 180 degrees inside the 560x800 crop
        assert (b.x0, b.y0) == pytest.approx((560 - (a.x1 - 20), 800 - (a.y1 - 12)), abs=0.05)


def test_cropped_page_is_shifted_by_the_crop_origin(pdfs: Path):
    base = pdfgen.paragraphs_pdf(pdfs / "base.pdf", ["Alfa beta gamma"] + ["riempitivo parola"] * 20)
    cropped = _variant(base, pdfs / "crop.pdf", lambda p: p.set_cropbox(20, 30, 580, 830))
    full, crop = extract(base), extract(cropped)
    assert [w.text for w in crop.words] == [w.text for w in full.words]
    assert crop.page_sizes[0] == pytest.approx((560, 800), abs=0.5)
    for a, b in zip(full.words, crop.words):
        # CropBox top-left is (20, 842 - 830 = 12) in top-left page points.
        assert (b.x0, b.y0) == pytest.approx((a.x0 - 20, a.y0 - 12), abs=0.05)


def test_text_cropped_away_is_dropped(pdfs: Path):
    base = pdfgen.paragraphs_pdf(pdfs / "base.pdf", ["Alfa beta gamma"] + ["riempitivo parola"] * 20)
    cropped = _variant(base, pdfs / "crop.pdf", lambda p: p.set_cropbox(0, 0, 595, 780))  # top 62 pt gone
    assert [w.text for w in extract(cropped).words][:2] == ["riempitivo", "parola"]


def test_an_unreadable_file_raises_a_readable_error(tmp_path: Path):
    from qtrequestory.officina.pdf import PdfReadError

    bad = tmp_path / "not-a.pdf"
    bad.write_bytes(b"<html>gateway error</html>")
    with pytest.raises(PdfReadError, match="impossibile leggere il PDF not-a.pdf"):
        extract(bad)
    assert issubclass(PdfReadError, ValueError)
    with pytest.raises(FileNotFoundError):
        extract(tmp_path / "missing.pdf")


def test_a_glyph_without_unicode_keeps_its_word_whole(monkeypatch):
    from qtrequestory.officina import pdf

    chars = [("a", (0, 0, 5, 10), (0, 0, 5, 10)), ("\ufffd", (5, 0, 10, 10), (5, 0, 10, 10)),
             ("b", (10, 0, 15, 10), (10, 0, 15, 10))]
    monkeypatch.setattr(pdf, "read_chars", lambda path: [pdf.PageChars(100, 100, chars, 0)])
    assert [w.text for w in extract(Path("x.pdf")).words] == ["a\ufffdb"]
