"""qtrequestory.officina.compare.pipeline: the staged comparison (spec §4).

Left = TARGET, right = a generated version. PDFs are generated by Qt from
synthetic text (tests/officina/pdfgen.py); the long-document budget uses
synthetic words directly.
"""
from __future__ import annotations

import logging
import time
from dataclasses import replace
from pathlib import Path

import pytest

from qtrequestory.officina.compare.classify import counts
from qtrequestory.officina.compare.extract_pdf import DocText, extract
from qtrequestory.officina.compare.model import Block, Comparison, Word
from qtrequestory.officina.compare.noise import PRESETS
from qtrequestory.officina.compare.pipeline import compare_docs
from qtrequestory.officina.model_review import NoiseRule
from tests.officina import pdfgen

log = logging.getLogger(__name__)

BASE = [
    "Condizioni generali di fornitura per il cliente di prova.",
    "Il prezzo della componente servizio resta fisso per dodici mesi.",
    "Le comunicazioni arrivano all'indirizzo example.invalid indicato nel modulo.",
]
LEGAL = ("Informativa sul trattamento dei dati personali ai sensi del regolamento europeo: il titolare "
         "tratta i dati per le finalità indicate nel contratto e li conserva per il tempo necessario.")
ROW = "Nome .......... Cognome .........."


def _pdf(pdfs: Path, name: str, paragraphs: list[str], **kw) -> DocText:
    return extract(pdfgen.paragraphs_pdf(pdfs / name, paragraphs, **kw))


def _html(pdfs: Path, name: str, html: str, **kw) -> DocText:
    return extract(pdfgen.html_pdf(pdfs / name, html, **kw))


def _summary(result: Comparison) -> list[tuple[str, str]]:
    return [(d.op, d.klass) for d in result.diffs]


def _counting(result: Comparison, profile: str = "tollerante") -> list:
    return [d for d in result.diffs if counts(d, profile)]  # type: ignore[arg-type]


# ------------------------------------------------------------ PDFs ---

def test_identical_documents_have_no_difference(pdfs: Path):
    result = compare_docs(_pdf(pdfs, "a.pdf", BASE), _pdf(pdfs, "b.pdf", BASE))
    assert result.diffs == () and result.note == ""
    assert result.left_has_text and result.right_has_text
    assert (result.left_pages, result.right_pages) == (1, 1)


def test_one_changed_letter_is_one_cambiato_with_spans_on_the_letter(pdfs: Path):
    target = _pdf(pdfs, "t.pdf", BASE)
    changed = _pdf(pdfs, "g.pdf", [BASE[0], BASE[1].replace("dodici", "dodoci"), BASE[2]])
    result = compare_docs(target, changed)
    assert _summary(result) == [("cambiato", "testo")]
    diff = result.diffs[0]
    assert diff.id == 1
    assert (diff.left_text, diff.right_text) == ("dodici", "dodoci")
    assert (diff.left_spans, diff.right_spans) == (((3, 4),), ((3, 4),))
    assert diff.left == tuple(w for w in target.words if w.text == "dodici")
    assert diff.anchor.target_text == "dodici"
    assert diff.anchor.context == "resta fisso per mesi. Le comunicazioni"


def test_text_reflowed_onto_the_next_page_is_no_difference(pdfs: Path):
    paragraphs = [pdfgen.lorem(110, seed=n) for n in range(7)]
    target = _pdf(pdfs, "t.pdf", paragraphs, font_pt=11)
    reflowed = _pdf(pdfs, "g.pdf", paragraphs, font_pt=11, width_mm=150)
    assert len(target.page_sizes) == len(reflowed.page_sizes) == 2, "same page count"
    first_on_2 = [w.text for w in reflowed.words if w.page == 1][0]
    assert next(w.page for w in target.words if w.text == first_on_2) == 0, "the fixture must really reflow"
    result = compare_docs(target, reflowed)
    assert result.diffs == (), _summary(result)


def test_a_filled_sure_slot_is_one_variable_and_nothing_counts(pdfs: Path):
    target = _html(pdfs, "t.pdf", "<p>Località ..........</p><p>Firma del cliente</p>")
    filled = _html(pdfs, "g.pdf", "<p>Località Springfield</p><p>Firma del cliente</p>")
    result = compare_docs(target, filled)
    assert _summary(result) == [("cambiato", "variabile")]
    assert result.diffs[0].right_text == "Springfield"
    assert result.slots_found == 1
    assert all(not _counting(result, p) for p in ("tollerante", "stretto", "solo_testo"))


def test_a_probable_slot_with_a_long_sentence_stays_testo(pdfs: Path):
    target = _html(pdfs, "t.pdf", "<p>Note:</p><p>Firma del cliente</p>")
    sentence = "questa frase è molto più lunga delle sei parole che uno slot probabile accetta"
    filled = _html(pdfs, "g.pdf", f"<p>Note: {sentence}</p><p>Firma del cliente</p>")
    result = compare_docs(target, filled)
    assert _summary(result) == [("in_piu", "testo")]
    assert result.diffs[0].right_text == sentence


@pytest.mark.parametrize("layout", ["paragraphs", "one_block"])
def test_repeated_slot_rows_are_all_variables(pdfs: Path, layout: str):
    """Review Focus 1: ten identical form rows, every value a variable."""
    intro, outro = pdfgen.lorem(40, seed=1), pdfgen.lorem(30, seed=2)
    target = _pdf(pdfs, "t.pdf", [intro] + [ROW] * 10 + [outro])
    rows = [f"Nome Anna{k} Cognome Neri{k}" for k in range(10)]
    if layout == "paragraphs":
        generated = _pdf(pdfs, "g.pdf", [intro] + rows + [outro])
    else:  # consecutive filled rows at normal pitch: ONE generated block
        generated = _html(pdfs, "g.pdf", f"<p>{intro}</p><p>{'<br>'.join(rows)}</p><p>{outro}</p>")
    result = compare_docs(target, generated)
    assert _summary(result) == [("cambiato", "variabile")] * 20
    assert [d.right_text for d in result.diffs] == [v for k in range(10) for v in (f"Anna{k}", f"Neri{k}")]
    assert len({d.anchor for d in result.diffs}) == 20
    assert result.slots_found == 20


def test_wingdings_box_against_ticked_and_empty_brackets(pdfs: Path):
    symbol = pdfgen.load_extra_font("symbol")
    if symbol is None:
        pytest.skip("no Wingdings font on this system")
    try:
        target = _html(pdfs, "t.pdf", "<p>Scelta del cliente:</p>" + pdfgen.checkbox_html("Opzione uno")
                       + pdfgen.checkbox_html("Opzione due"))
    finally:
        pdfgen.unload_font(symbol)
    ticked = _html(pdfs, "x.pdf", "<p>Scelta del cliente:</p><p>[x] Opzione uno</p><p>[ ] Opzione due</p>")
    result = compare_docs(target, ticked)
    assert _summary(result) == [("cambiato", "testo")], "the state differs"
    assert result.diffs[0].right_text == "[ x ]" or result.diffs[0].right_text.replace(" ", "") == "[x]"
    empty = _html(pdfs, "e.pdf", "<p>Scelta del cliente:</p><p>[ ] Opzione uno</p><p>[ ] Opzione due</p>")
    assert compare_docs(target, empty).diffs == ()


def test_a_comb_field_equals_the_plain_value(pdfs: Path):
    target = extract(pdfgen.comb_pdf(pdfs / "t.pdf", "IBAN", "IT60X0542811101"))
    generated = _html(pdfs, "g.pdf", "<p>IBAN IT60X0542811101</p>")
    assert compare_docs(target, generated).diffs == ()


def test_a_missing_section_is_one_sezione_assente(pdfs: Path):
    section = pdfgen.lorem(80, seed=5)
    target = _pdf(pdfs, "t.pdf", [BASE[0], section, BASE[1], BASE[2]])
    result = compare_docs(target, _pdf(pdfs, "g.pdf", BASE))
    assert _summary(result) == [("sezione_assente", "composizione")]
    diff = result.diffs[0]
    assert diff.left_text == section and diff.right == ()
    lines = len({round(w.y1) for w in diff.left})
    assert lines >= 2 and diff.detail == f"{lines} righe"
    assert diff.anchor.context.endswith("Il prezzo della")


def test_an_extra_section_is_one_sezione_in_piu(pdfs: Path):
    section = pdfgen.lorem(80, seed=6)
    result = compare_docs(_pdf(pdfs, "t.pdf", BASE), _pdf(pdfs, "g.pdf", [BASE[0], section, BASE[1], BASE[2]]))
    assert _summary(result) == [("sezione_in_piu", "composizione")]
    assert result.diffs[0].anchor.context == "prova. Il", "the two target neighbours"
    assert result.diffs[0].anchor.target_text == ""


def test_a_moved_paragraph_is_one_spostato(pdfs: Path):
    body = [pdfgen.lorem(45, seed=s) for s in (11, 12, 13)]
    result = compare_docs(_pdf(pdfs, "t.pdf", [LEGAL] + body), _pdf(pdfs, "g.pdf", body + [LEGAL]))
    assert _summary(result) == [("spostato", "composizione")]
    diff = result.diffs[0]
    assert diff.left_text == diff.right_text == LEGAL
    assert diff.left[0].y0 < diff.right[0].y0


def test_an_extra_page_is_one_pagine(pdfs: Path):
    target = _pdf(pdfs, "t.pdf", BASE)
    longer = _html(pdfs, "g.pdf", "".join(f"<p>{p}</p>" for p in BASE)
                   + '<p style="page-break-before: always">&nbsp;</p>')
    assert len(longer.page_sizes) == 2
    result = compare_docs(target, longer)
    assert _summary(result) == [("pagine", "composizione")]
    diff = result.diffs[0]
    assert (diff.left_text, diff.right_text, diff.detail) == ("1 pagina", "2 pagine", "1 pagina contro 2")
    assert counts(diff, "tollerante")


def test_a_bold_word_is_stile_counting_only_in_stretto(pdfs: Path):
    bold = pdfgen.load_extra_font("bold")
    if bold is None:
        pytest.skip("no bold face of the test font on this system")
    try:
        runs = [("Il prezzo della componente", 11.0, False), ("resta", 11.0, False), ("fisso per dodici mesi.", 11.0, False)]
        target = _html(pdfs, "t.pdf", pdfgen.runs_html(runs))
        runs[1] = ("resta", 11.0, True)
        generated = _html(pdfs, "g.pdf", pdfgen.runs_html(runs))
    finally:
        pdfgen.unload_font(bold)
    result = compare_docs(target, generated)
    assert _summary(result) == [("cambiato", "stile")]
    assert result.diffs[0].left_text == result.diffs[0].right_text == "resta"
    assert not _counting(result, "tollerante") and not _counting(result, "solo_testo")
    assert len(_counting(result, "stretto")) == 1


ON = [replace(p, enabled=True) for p in PRESETS if p.name in ("Data", "Numero di pagina", "Importo")]


def test_deterministic(pdfs: Path):
    target = _pdf(pdfs, "t.pdf", [LEGAL] + BASE + [ROW] * 3 + ["Emesso il 01/02/2026, pag. 1 di 2."])
    generated = _pdf(pdfs, "g.pdf", [BASE[0], BASE[1].replace("dodici", "ventiquattro")] + [LEGAL]
                     + ["Nome Anna Cognome Neri"] * 3 + ["Emesso il 3 marzo 2026, pag. 1 di 3."])
    first = compare_docs(target, generated, rules=ON)
    assert first == compare_docs(target, generated, rules=ON)
    assert {"variabile", "rumore", "testo", "composizione"} <= {d.klass for d in first.diffs}
    assert dict(first.noise_hits)["Data"] == 2
    assert [d.id for d in first.diffs] == list(range(1, len(first.diffs) + 1))


def test_two_ten_page_pdfs_under_budget(pdfs: Path):
    paragraphs = [pdfgen.lorem(90, seed=n) for n in range(75)]
    edited = list(paragraphs)
    edited[10] = edited[10].replace(edited[10].split()[3], "modificata", 1)
    del edited[30]
    edited.insert(45, "Paragrafo nuovo di prova.")
    pdfgen.paragraphs_pdf(pdfs / "a.pdf", paragraphs, font_pt=11)
    pdfgen.paragraphs_pdf(pdfs / "b.pdf", edited, font_pt=11)
    started = time.perf_counter()
    a, b = extract(pdfs / "a.pdf"), extract(pdfs / "b.pdf")
    extracted = time.perf_counter()
    result = compare_docs(a, b)
    done = time.perf_counter()
    elapsed = done - started
    message = (f"two 10-page PDFs: {elapsed:.2f} s (extract {extracted - started:.2f} s, "
               f"compare_docs {done - extracted:.2f} s)")
    log.warning(message)
    print()
    print(message)
    assert len(a.page_sizes) >= 10
    assert elapsed < 5, f"extract + compare of two 10-page PDFs took {elapsed:.2f} s (spec: < 3 s)"
    assert sorted(d.op for d in result.diffs) == ["cambiato", "in_piu", "sezione_assente"]


# ----------------------------------------------------- synthetic words ---

def _doc(*paragraphs: str, pages: int = 1, lines_per_page: int = 48, size: float = 11.0) -> DocText:
    """Paragraphs laid out on lines of ≤ 12 words, 14 pt apart, a blank line
    between paragraphs, a new page every ``lines_per_page`` lines."""
    words: list[Word] = []
    line = 0
    for paragraph in paragraphs:
        tokens = paragraph.split()
        for start in range(0, len(tokens), 12):
            page, row = divmod(line, lines_per_page)
            y, x = 50.0 + 14.0 * row, 40.0
            for token in tokens[start:start + 12]:
                words.append(Word(token, page, x, y, x + 5.0 * len(token), y + 11.0, size))
                x += 5.0 * (len(token) + 1)
            line += 1
        line += 1
    pages = max(pages, (words[-1].page + 1) if words else 1)
    return DocText(words, [(595.0, 842.0)] * pages, bool(words))


def test_a_side_without_text_is_noted_not_diffed():
    empty = DocText([], [(595.0, 842.0)], False)
    result = compare_docs(empty, _doc(*BASE))
    assert result.diffs == () and not result.left_has_text and result.right_has_text
    assert result.note == "il target non ha testo estraibile"
    assert compare_docs(_doc(*BASE), empty, right_label="AS-IS").note == "l'AS-IS non ha testo estraibile"


def test_noise_rules_make_dates_rumore_and_bad_rules_are_noted():
    target = _doc("Documento emesso il 01/02/2026. Pagina di prova.")
    generated = _doc("Documento emesso il 1 febbraio 2026. Pagina di prova.")
    assert _summary(compare_docs(target, generated)) == [("cambiato", "testo")]
    rules = [*PRESETS[:2], NoiseRule("Data", r"\d{2}/\d{2}/\d{4}", True), NoiseRule("Rotta", "(", True)]
    rules[1] = NoiseRule(PRESETS[1].name, PRESETS[1].pattern, True)
    result = compare_docs(target, generated, rules=rules)
    assert _summary(result) == [("cambiato", "rumore")]
    assert result.diffs[0].left_text == "01/02/2026." and result.diffs[0].right_text == "1 febbraio 2026."
    assert result.noise_hits == (("Data", 2),)
    assert "regola «Rotta» ignorata: espressione non valida" in result.note
    assert "regola «Data» ignorata: nome già usato" in result.note


def test_a_switched_off_slot_makes_the_value_a_text_difference():
    target, filled = _doc("Località ..........", "Firma"), _doc("Località Springfield", "Firma")
    variable = compare_docs(target, filled).diffs[0]
    result = compare_docs(target, filled, disabled_slots=[variable.anchor])
    assert _summary(result) == [("cambiato", "testo")]
    assert result.slots_found == 0
    assert (result.diffs[0].left_text, result.diffs[0].right_text) == ("..........", "Springfield")


def test_split_words_are_spaziatura():
    result = compare_docs(_doc("Il contratto di fornitura resta valido"), _doc("Il contratto di forni tura resta valido"))
    assert _summary(result) == [("cambiato", "spaziatura")]
    assert not _counting(result) and len(_counting(result, "stretto")) == 1


def test_a_phrase_moved_inside_its_paragraph_is_one_spostato():
    moved = "il cliente può recedere in ogni momento"
    rest = "Le parti firmano il presente documento di prova per accettazione integrale del testo."
    a = f"Premessa del contratto di prova. {moved}. {rest}"
    b = f"Premessa del contratto di prova. {rest} {moved}."
    result = compare_docs(_doc(a), _doc(b))
    assert _summary(result) == [("spostato", "composizione")]
    assert result.diffs[0].left_text == result.diffs[0].right_text == moved + "."


def test_block_lists_are_compared_as_they_are():
    def blocks(*texts: str) -> list[Block]:
        return [Block(k, tuple(Word(t, 0, 0.0, 0.0, 0.0, 0.0) for t in text.split()), 0, "html")
                for k, text in enumerate(texts)]
    missing = [pdfgen.lorem(12, seed=3), pdfgen.lorem(15, seed=4)]
    result = compare_docs(blocks(BASE[0], *missing, BASE[1]), blocks(BASE[0], BASE[1].replace("dodici", "sei")))
    assert _summary(result) == [("sezione_assente", "composizione"), ("cambiato", "testo")]
    assert result.diffs[0].detail == "2 righe"
    assert (result.left_pages, result.right_pages) == (1, 1)
    assert compare_docs(blocks(), blocks(BASE[0])).note == "il target non ha testo estraibile"


def test_anchors_are_distinct_and_numbered_in_target_order():
    rows = [f"Riga {k} del modulo con testo fisso" for k in range(4)]
    target = _doc(*rows, *rows)
    generated = _doc(*[r.replace("fisso", "fissa") for r in rows], *[r.replace("fisso", "fissa") for r in rows])
    result = compare_docs(target, generated)
    assert len(result.diffs) == 8 and len({d.anchor for d in result.diffs}) == 8
    assert [d.id for d in result.diffs] == list(range(1, 9))
    assert result.diffs[4].anchor.context.endswith("#2")


def test_sixty_pages_under_budget():
    """Review Focus 5: 60 pages, ~40 blocks a page, comparison under 10 s."""
    blocks = []
    for k in range(2400):
        if k % 25 == 0:
            blocks.append(ROW)
        elif k % 7 == 0:
            blocks.append(f"{pdfgen.lorem(8, seed=k)} il 0{1 + k % 9}/02/2026 importo € {k},00")
        else:
            blocks.append(pdfgen.lorem(8 + k % 5, seed=k))
    generated = []
    for k, text in enumerate(blocks):
        if k % 97 == 5:
            continue                                   # missing block
        if text == ROW:
            text = f"Nome Anna{k} Cognome Neri{k}"
        elif "/02/2026" in text:
            text = text.replace("/02/", "/03/").replace(f"€ {k},00", f"€ {k + 1},00")
        elif k % 13 == 0:
            text = text.replace(text.split()[1], "cambiata", 1)
        generated.append(text)
        if k % 150 == 7:
            generated.append(pdfgen.lorem(10, seed=10_000 + k))   # extra block
    target = _doc(*blocks, lines_per_page=80)
    other = _doc(*generated, lines_per_page=80)
    assert len(target.page_sizes) >= 60
    started = time.perf_counter()
    result = compare_docs(target, other, rules=ON)
    elapsed = time.perf_counter() - started
    log.warning("sixty pages: compare_docs in %.2f s", elapsed)
    print(f"\nsixty pages: compare_docs in {elapsed:.2f} s ({len(result.diffs)} differences)")
    assert elapsed < 10, f"60 pages took {elapsed:.2f} s"
    klasses = {d.klass for d in result.diffs}
    assert {"variabile", "testo", "rumore"} <= klasses
    assert not [d for d in result.diffs if d.op == "spostato"]
    assert sum(1 for d in result.diffs if d.klass == "variabile") == 2 * sum(1 for t in generated if "Anna" in t)


# ------------------------------------------ fix round 1 (R26, R27) ---

def test_a_weak_out_of_order_pair_is_no_move_and_no_duplicate():
    """R26: the amount glued to the previous block on the generated side; the
    target's own amount block pairs (weakly) with a far generated one."""
    body = [pdfgen.lorem(30, seed=s) for s in range(8)]
    target = _doc(body[0], "importo € 112,00", *body[1:8])
    generated = _doc(body[0] + " importo € 112,00", *body[1:6], "importo € 301,00", *body[6:8])
    result = compare_docs(target, generated)
    assert _summary(result) == [("in_piu", "testo")]
    assert result.diffs[0].right_text == "importo € 301,00"


def test_dates_and_amounts_changed_across_pages_give_no_move():
    on = [replace(p, enabled=True) for p in PRESETS]
    target, generated = [], []
    for k in range(300):
        text = pdfgen.lorem(8 + k % 5, seed=k)
        if k % 7 == 0:
            target += [text, f"il 0{1 + k % 9}/02/2026 importo € {k},00"]
            generated += [f"{text} il 0{1 + k % 9}/03/2026 importo € {k * 3 % 400},00"]
        else:
            target.append(text)
            generated.append(text)
    for rules in ((), on):
        result = compare_docs(_doc(*target, lines_per_page=60), _doc(*generated, lines_per_page=60), rules=rules)
        assert not [d for d in result.diffs if d.op == "spostato"], rules
        seen: list[int] = [id(w) for d in result.diffs for w in d.right]
        assert len(seen) == len(set(seen)), "a generated word is reported twice"


def test_a_moved_identical_paragraph_is_still_one_spostato():
    body = [pdfgen.lorem(30, seed=s) for s in range(6)]
    result = compare_docs(_doc(LEGAL, *body), _doc(*body[:3], LEGAL, *body[3:]))
    assert _summary(result) == [("spostato", "composizione")]


SECTION = ("Questa sezione del contratto di prova vale solo per chi sceglie il pagamento "
           "anticipato delle fatture di ogni mese")


@pytest.mark.parametrize("neighbour", ["next_word", "previous_word"])
def test_a_missing_section_next_to_a_change_is_one_section_and_one_change(neighbour: str):
    """R27: an unmatched target block is a hard boundary of the word diff."""
    intro, price = "Premessa del contratto di prova tra le parti.", "Il prezzo resta fisso per dodici mesi."
    target = _doc(intro, SECTION, price)
    if neighbour == "next_word":
        generated = _doc(intro, price.replace("Il", "Lo", 1))
        expected = [("sezione_assente", "composizione"), ("cambiato", "testo")]
    else:
        generated = _doc(intro + " Aggiunta", price)
        expected = [("in_piu", "testo"), ("sezione_assente", "composizione")]
    result = compare_docs(target, generated)
    assert _summary(result) == expected
    section = next(d for d in result.diffs if d.op == "sezione_assente")
    assert section.left_text == SECTION and section.detail == "2 righe"
    other = next(d for d in result.diffs if d.op != "sezione_assente")
    assert other.left_text in ("Il", "") and other.right_text in ("Lo", "Aggiunta")


def test_an_extra_section_next_to_a_change_is_one_section_and_one_change():
    intro, price = "Premessa del contratto di prova tra le parti.", "Il prezzo resta fisso per dodici mesi."
    result = compare_docs(_doc(intro, price), _doc(intro, SECTION, price.replace("Il", "Lo", 1)))
    assert _summary(result) == [("sezione_in_piu", "composizione"), ("cambiato", "testo")]
    assert result.diffs[0].right_text == SECTION


def test_a_bold_paragraph_is_one_stile_diff():
    bold = _doc("Il prezzo della componente servizio resta fisso per dodici mesi " * 3)
    words = [replace(w, bold=True) for w in bold.words]
    result = compare_docs(bold, DocText(words, bold.page_sizes, True))
    assert _summary(result) == [("cambiato", "stile")]


def test_rumore_and_variabile_diffs_have_no_char_spans():
    on = [replace(p, enabled=True) for p in PRESETS if p.name == "Data"]
    result = compare_docs(_doc("Emesso il 01/02/2026.", "Località .........."),
                          _doc("Emesso il 3 marzo 2026.", "Località Springfield"), rules=on)
    assert _summary(result) == [("cambiato", "rumore"), ("cambiato", "variabile")]
    assert all(d.left_spans == () and d.right_spans == () for d in result.diffs)


# ------------------------------------------------ fix round 2 (R27) ---

@pytest.mark.parametrize(("before", "after"), [
    ("Premessa", "Introduzione"), ("Roma", "Milano"), ("Mario Rossi", "Anna Neri")])
def test_a_replaced_standalone_line_is_one_cambiato(before: str, after: str):
    body = [pdfgen.lorem(30, seed=s) for s in range(4)]
    result = compare_docs(_doc(body[0], before, *body[1:]), _doc(body[0], after, *body[1:]))
    assert _summary(result) == [("cambiato", "testo")]
    assert (result.diffs[0].left_text, result.diffs[0].right_text) == (before, after)


def test_a_changed_date_line_glued_to_the_previous_paragraph_is_one_cambiato():
    body = [pdfgen.lorem(30, seed=s) for s in range(3)]
    target = _doc(body[0], "01/02/2026", *body[1:])
    generated = _doc(body[0] + " 02/02/2026", *body[1:])
    result = compare_docs(target, generated)
    assert _summary(result) == [("cambiato", "testo")]
    assert (result.diffs[0].left_text, result.diffs[0].right_text) == ("01/02/2026", "02/02/2026")


def test_both_neighbours_of_a_missing_section_changed_are_credited_to_their_own_words():
    intro, price = "Premessa del contratto tra le parti.", "Il prezzo resta fisso per dodici mesi."
    target = _doc(intro, SECTION, price)
    generated = _doc(intro.replace("parti.", "persone."), price.replace("Il", "Lo", 1))
    result = compare_docs(target, generated)
    assert [(d.op, d.left_text, d.right_text) for d in result.diffs] == [
        ("cambiato", "parti.", "persone."), ("sezione_assente", SECTION, ""), ("cambiato", "Il", "Lo")]


# ------------------------------------------- display context (R33) and trims (E7) ---

def test_a_change_carries_up_to_five_target_words_of_context_on_each_side():
    text = "Il prezzo della componente servizio resta fisso per dodici mesi dalla firma."
    result = compare_docs(_doc(text), _doc(text.replace("dodici", "sei")))
    diff = result.diffs[0]
    assert (diff.left_text, diff.right_text) == ("dodici", "sei")
    assert diff.context_before == "componente servizio resta fisso per"
    assert diff.context_after == "mesi dalla firma."


def test_an_insertion_is_framed_by_the_target_words_around_it():
    result = compare_docs(_doc("Uno due tre quattro cinque sei."), _doc("Uno due tre NUOVO quattro cinque sei."))
    diff = result.diffs[0]
    assert diff.op == "in_piu"
    assert (diff.context_before, diff.context_after) == ("Uno due tre", "quattro cinque sei.")


def test_context_stays_in_the_block_and_falls_back_to_the_neighbours_for_a_whole_block():
    intro, price = "Premessa del contratto di prova tra le parti.", "Il prezzo resta fisso per dodici mesi."
    changed = compare_docs(_doc(intro, price), _doc(intro, price.replace("Il", "Lo", 1))).diffs[0]
    assert changed.context_before == "di prova tra le parti."  # starts its block: the neighbour's words
    assert changed.context_after == "prezzo resta fisso per dodici"
    section = next(d for d in compare_docs(_doc(intro, SECTION, price), _doc(intro, price)).diffs
                   if d.op == "sezione_assente")
    assert section.context_before == "di prova tra le parti."
    assert section.context_after == "Il prezzo resta fisso per"


def test_the_context_is_display_only_and_never_moves_the_anchor():
    text = "Il prezzo della componente servizio resta fisso per dodici mesi dalla firma."
    diff = compare_docs(_doc(text), _doc(text.replace("dodici", "sei"))).diffs[0]
    assert diff.anchor.context == "resta fisso per mesi dalla firma."


# ------------------------------------------------------ HTML links (E7) ---

def _html_blocks(html: str):
    from qtrequestory.officina.compare.extract_html import extract_html

    return extract_html(html.encode())[0]


def test_a_changed_href_is_one_link_diff_that_counts():
    target = _html_blocks('<body><p>Leggi le <a href="https://example.invalid/a">condizioni</a> ora.</p></body>')
    tobe = _html_blocks('<body><p>Leggi le <a href="https://example.invalid/b">condizioni</a> ora.</p></body>')
    result = compare_docs(target, tobe)
    assert _summary(result) == [("cambiato", "link")]
    diff = result.diffs[0]
    assert diff.detail == "href: https://example.invalid/a → https://example.invalid/b"
    assert (diff.left_text, diff.right_text) == ("https://example.invalid/a", "https://example.invalid/b")
    assert diff.anchor.klass == "link" and diff.anchor.target_text == "href: https://example.invalid/a"
    assert [w.text for w in diff.left] == ["Leggi", "le", "condizioni", "ora."]
    assert counts(diff, "tollerante") and counts(diff, "stretto") and not counts(diff, "solo_testo")


def test_tracking_parameters_are_dropped_only_with_the_rule():
    from qtrequestory.officina.compare import urls

    target = _html_blocks('<body><p><a href="https://example.invalid/p?id=1">Vai</a></p></body>')
    tobe = _html_blocks('<body><p><a href="https://example.invalid/p?id=1&utm_source=x">Vai</a></p></body>')
    assert _summary(compare_docs(target, tobe)) == [("cambiato", "link")]
    assert compare_docs(target, tobe, link_drop=urls.tracking_drop).diffs == ()


def test_an_image_only_block_gone_is_a_link_diff_and_anchors_stay_unique():
    target = _html_blocks('<body><p>Testo uguale</p><p><img src="https://example.invalid/l.png" alt="Logo"></p>'
                          '<p>Fine uguale</p></body>')
    tobe = _html_blocks('<body><p>Testo uguale</p><p>Fine uguale</p></body>')
    result = compare_docs(target, tobe)
    assert [(d.op, d.klass, d.detail) for d in result.diffs] == [
        ("cambiato", "link", "src: https://example.invalid/l.png → (assente)"),
        ("cambiato", "link", "alt: Logo → (assente)")]
    assert len({d.anchor for d in result.diffs}) == 2
    assert [d.id for d in result.diffs] == [1, 2]


def test_pdf_sides_never_get_link_diffs():
    result = compare_docs(_doc(*BASE), _doc(*BASE))
    assert result.diffs == ()


# ------------------------------------ HTML without boxes: block ends are line ends (final review I1) ---

def _boxed(html: str) -> tuple[Block, ...]:
    """The blocks of ``html`` with synthetic boxes: one printed line per block."""
    out = []
    for b, block in enumerate(_html_blocks(html)):
        words = tuple(replace(w, page=0, x0=10 + 40 * k, x1=40 + 40 * k, y0=20 * b, y1=20 * b + 10)
                      for k, w in enumerate(block.words))
        out.append(replace(block, words=words))
    return tuple(out)


@pytest.mark.parametrize("boxes", [False, True], ids=["no boxes", "boxes"])
def test_a_label_alone_in_its_block_is_a_probable_slot_without_boxes_too(boxes: bool):
    make = _boxed if boxes else _html_blocks
    target = make("<p>Riferimento:</p><p>Gentile cliente, la informiamo</p>")
    tobe = make("<p>Riferimento: il contratto scade</p><p>Gentile cliente, la informiamo</p>")
    result = compare_docs(target, tobe)
    assert _summary(result) == [("cambiato", "variabile")] and result.slots_found == 1
    assert result.diffs[0].right_text == "il contratto scade"


@pytest.mark.parametrize("boxes", [False, True], ids=["no boxes", "boxes"])
def test_a_sure_slot_never_swallows_an_inserted_paragraph_without_boxes(boxes: bool):
    make = _boxed if boxes else _html_blocks
    target = make("<p>Nome ..........</p><p>Il canone mensile resta invariato per un anno</p>"
                  "<p>Coda comune finale del documento</p>")
    tobe = make("<p>Nome Mario</p><p>Premessa aggiuntiva non prevista dal cliente</p>"
                "<p>Il canone mensile resta invariato per un anno</p><p>Coda comune finale del documento</p>")
    result = compare_docs(target, tobe)
    assert [(d.op, d.klass, d.right_text) for d in result.diffs] == [
        ("cambiato", "variabile", "Mario"),
        ("in_piu", "testo", "Premessa aggiuntiva non prevista dal cliente")]
