"""qtrequestory.officina.compare.normalise: tokens → comparison units.

Words are synthetic (built here, or extracted from PDFs generated by
tests/officina/pdfgen.py).
"""
from __future__ import annotations

from pathlib import Path

import pytest

from qtrequestory.officina.compare.extract_pdf import Word, extract
from qtrequestory.officina.compare.normalise import CHECK_OFF, CHECK_ON, normalise_token, units
from tests.officina import pdfgen


def _line(*tokens: str, y: float = 50.0, pitch: float = 30.0, x: float = 40.0, width: float = 25.0) -> list[Word]:
    """One line of words, ``pitch`` points apart."""
    return [Word(t, 0, x + pitch * i, y, x + pitch * i + width, y + 10) for i, t in enumerate(tokens)]


def _keys(words: list[Word]) -> list[str]:
    return units(words)[0]


# ------------------------------------------------------------ tokens ---

def test_normalise_token_follows_the_phase_one_rules():
    assert normalise_token("“ciao”") == '"ciao"'
    assert normalise_token("«ciao»") == '"ciao"'
    assert normalise_token("l’offerta") == "l'offerta"
    assert normalise_token("A–B") == "A-B" and normalise_token("A—B") == "A-B"
    assert normalise_token("ﬁne") == "fine"
    assert normalise_token("10 000") == "10000"
    assert normalise_token(" soft­hyphen​ ") == "softhyphen"
    assert normalise_token("Prezzo") == "Prezzo"


@pytest.mark.parametrize("glyph", ["❏", "☐", "□", "", ""])
def test_empty_box_glyphs_become_check_off(glyph: str):
    assert normalise_token(glyph) == CHECK_OFF
    assert _keys(_line(glyph, "Opzione")) == [CHECK_OFF, "Opzione"]


@pytest.mark.parametrize("glyph", ["☒", "☑", ""])
def test_ticked_box_glyphs_become_check_on(glyph: str):
    assert normalise_token(glyph) == CHECK_ON
    assert _keys(_line(glyph, "Opzione")) == [CHECK_ON, "Opzione"]


@pytest.mark.parametrize(("tokens", "key"), [
    (("[", "]"), CHECK_OFF), (("[]",), CHECK_OFF),
    (("[x]",), CHECK_ON), (("[X]",), CHECK_ON), (("[", "x", "]"), CHECK_ON), (("[", "X", "]"), CHECK_ON),
])
def test_bracket_boxes(tokens: tuple[str, ...], key: str):
    keys, members = units(_line(*tokens, "Opzione", "uno"))
    assert keys == [key, "Opzione", "uno"]
    assert [w.text for w in members[0]] == list(tokens)


def test_brackets_on_two_lines_are_not_a_box():
    words = _line("scelta", "[") + _line("]", "fine", y=70)
    assert CHECK_OFF not in _keys(words)


def test_a_lone_q_opening_a_list_line_is_a_box():
    words = _line("Scegli:") + _line("q", "Opzione", "uno", y=70) + _line("q", "Opzione", "due", y=90)
    assert _keys(words) == ["Scegli:", CHECK_OFF, "Opzione", "uno", CHECK_OFF, "Opzione", "due"]


def test_a_q_inside_a_sentence_is_untouched():
    assert _keys(_line("la", "lettera", "q", "resta")) == ["la", "lettera", "q", "resta"]
    # alone on its line (nothing follows it on the line): not a list item
    assert "q" in _keys(_line("lettera") + _line("q", y=70) + _line("altro", y=90))


def test_comb_field_collapses_into_one_unit():
    words = _line("IBAN") + _line(*"IT60X0542", y=70, pitch=14, width=7)
    keys, members = units(words)
    assert keys == ["IBAN", "IT60X0542"]
    assert len(members[1]) == 9, "the unit keeps every original box"


def test_irregular_single_letters_are_not_a_comb():
    xs = [40, 52, 90, 97]
    words = [Word(t, 0, x, 50, x + 6, 60) for t, x in zip("aeio", xs)]
    assert _keys(words) == ["a", "e", "i", "o"]


def test_three_single_letters_are_not_a_comb():
    assert _keys(_line("x", "y", "z", "fine", pitch=14, width=7)) == ["x", "y", "z", "fine"]


def test_a_comb_stops_at_the_line_end():
    words = _line(*"ABCD", pitch=14, width=7) + _line(*"EF", y=70, pitch=14, width=7)
    assert _keys(words) == ["ABCD", "E", "F"]


def test_comb_after_an_irregular_letter():
    words = [Word("e", 0, 10, 50, 16, 60)] + _line(*"1234", pitch=14, width=7, x=60)
    assert _keys(words) == ["e", "1234"]


def test_punctuation_sticks_and_hyphens_join():
    assert _keys(_line("Il", "prezzo", ",", "fisso", "(", "dodici", "mesi", ")", ".")) == [
        "Il", "prezzo,", "fisso", "(dodici", "mesi).",
    ]
    joined = _line("di", "forni-") + _line("tura", "valido", y=70)
    keys, members = units(joined)
    assert keys == ["di", "fornitura", "valido"]
    assert [w.text for w in members[1]] == ["forni-", "tura"]
    assert _keys(_line("di", "forni-", "tura")) == ["di", "forni-", "tura"]


def test_units_are_deterministic_and_tuples():
    words = _line("q", "Voce", ",", "[x]") + _line(*"AB12", y=70, pitch=14, width=7)
    first = units(words)
    assert first == units(words)
    assert all(isinstance(m, tuple) for m in first[1])


# ------------------------------------------------------------- PDFs ---

def test_wingdings_box_in_a_pdf_becomes_check_off(pdfs: Path):
    symbol = pdfgen.load_extra_font("symbol")
    if symbol is None:
        pytest.skip("no Wingdings font on this system")
    try:
        html = "<p>Scelta del cliente:</p>" + pdfgen.checkbox_html("Opzione uno") + pdfgen.checkbox_html("Opzione due")
        words = extract(pdfgen.html_pdf(pdfs / "box.pdf", html)).words
    finally:
        pdfgen.unload_font(symbol)
    assert _keys(words) == ["Scelta", "del", "cliente:", CHECK_OFF, "Opzione", "uno", CHECK_OFF, "Opzione", "due"]


def test_comb_field_in_a_pdf_is_one_unit(pdfs: Path):
    words = extract(pdfgen.comb_pdf(pdfs / "comb.pdf", "IBAN", "IT60X0542")).words
    assert [w.text for w in words] == ["IBAN", *"IT60X0542"]
    assert _keys(words) == ["IBAN", "IT60X0542"]


def test_double_prime_keeps_the_phase_one_form():
    # phase 1 ran NFKC first: ″ decomposes into two primes, each a quote
    assert normalise_token("″") == "''"
